// libraries
// import { useState } from "react";
// components
import TopNavigation from "../../components/navigation/topnavigation/TopNavigation";
import HistoryInfoCard from "../../components/content/list/History";
import ResourceDate from "../../components/content/list/Resource/Date";
// assets
import chevron_left from "../../assets/icons/chevron_left.svg";

export default function AllHistoryPage() {
  // mock data
  const historyData = [
    {
      year: 2026,
      showYear: true,
      monthDay: "12.27",
      items: [
        {
          timelineId: 2001,
          type: "FOCUS",
          occurredAt: "2026-12-27T23:10:00",
          title: "1시간 42분의 포커스",
          subtitle: "21:28 - 23:10",
          previewText: "1시간 42분의 포커스",
          targetId: 8001,
        },
        {
          timelineId: 2002,
          type: "RECORD",
          occurredAt: "2026-12-27T20:15:00",
          title: "작별하지 않는다",
          subtitle: "[p.212] 겨울의 감각이 오래 남았다.",
          previewText: "[p.212] 겨울의 감각이 오래 남았다.",
          targetId: 8002,
        },
        {
          timelineId: 2003,
          type: "STATUS",
          occurredAt: "2026-12-27T09:00:00",
          title: "독서 상태 변경",
          subtitle: "읽는 중으로 바뀌었어요.",
          previewText: "읽는 중으로 바뀌었어요.",
          targetId: 8003,
        },
      ],
    },
    {
      year: 2026,
      showYear: false,
      monthDay: "12.20",
      items: [
        {
          timelineId: 2004,
          type: "REGISTER",
          occurredAt: "2026-12-20T10:12:00",
          title: "소년이 온다",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8004,
        },
        {
          timelineId: 2005,
          type: "FOCUS",
          occurredAt: "2026-12-20T16:35:00",
          title: "56분의 포커스",
          subtitle: "15:39 - 16:35",
          previewText: "56분의 포커스",
          targetId: 8005,
        },
        {
          timelineId: 2006,
          type: "RECORD",
          occurredAt: "2026-12-20T22:41:00",
          title: "소년이 온다",
          subtitle: "[p.88] 문장이 짧은데도 마음을 오래 잡아둔다.",
          previewText: "[p.88] 문장이 짧은데도 마음을 오래 잡아둔다.",
          targetId: 8006,
        },
      ],
    },
    {
      year: 2026,
      showYear: false,
      monthDay: "12.09",
      items: [
        {
          timelineId: 2007,
          type: "FOCUS",
          occurredAt: "2026-12-09T23:15:00",
          title: "1시간 13분의 포커스",
          subtitle: "22:02 - 23:15",
          previewText: "1시간 13분의 포커스",
          targetId: 8007,
        },
        {
          timelineId: 2008,
          type: "FOCUS",
          occurredAt: "2026-12-09T16:50:00",
          title: "1시간 27분의 포커스",
          subtitle: "15:23 - 16:50",
          previewText: "1시간 27분의 포커스",
          targetId: 8008,
        },
        {
          timelineId: 2009,
          type: "RECORD",
          occurredAt: "2026-12-09T10:20:00",
          title: "밝은 밤",
          subtitle: "[p.131] 어느 쪽의 이야기가 더 오래 남을까 생각했다.",
          previewText: "[p.131] 어느 쪽의 이야기가 더 오래 남을까 생각했다.",
          targetId: 8009,
        },
        {
          timelineId: 2010,
          type: "STATUS",
          occurredAt: "2026-12-09T08:40:00",
          title: "독서 상태 변경",
          subtitle: "완독으로 바뀌었어요.",
          previewText: "완독으로 바뀌었어요.",
          targetId: 8010,
        },
      ],
    },
    {
      year: 2026,
      showYear: false,
      monthDay: "11.28",
      items: [
        {
          timelineId: 2011,
          type: "REGISTER",
          occurredAt: "2026-11-28T13:02:00",
          title: "달러구트 꿈 백화점",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8011,
        },
        {
          timelineId: 2012,
          type: "FOCUS",
          occurredAt: "2026-11-28T22:14:00",
          title: "43분의 포커스",
          subtitle: "21:31 - 22:14",
          previewText: "43분의 포커스",
          targetId: 8012,
        },
        {
          timelineId: 2013,
          type: "STATUS",
          occurredAt: "2026-11-28T18:10:00",
          title: "독서 상태 변경",
          subtitle: "잠시 멈춤으로 바뀌었어요.",
          previewText: "잠시 멈춤으로 바뀌었어요.",
          targetId: 8013,
        },
      ],
    },
    {
      year: 2026,
      showYear: false,
      monthDay: "11.14",
      items: [
        {
          timelineId: 2014,
          type: "RECORD",
          occurredAt: "2026-11-14T22:08:00",
          title: "아몬드",
          subtitle: "[p.57] 감정을 설명하는 방식이 인상적이었다.",
          previewText: "[p.57] 감정을 설명하는 방식이 인상적이었다.",
          targetId: 8014,
        },
        {
          timelineId: 2015,
          type: "FOCUS",
          occurredAt: "2026-11-14T20:00:00",
          title: "1시간 5분의 포커스",
          subtitle: "18:55 - 20:00",
          previewText: "1시간 5분의 포커스",
          targetId: 8015,
        },
        {
          timelineId: 2016,
          type: "RECORD",
          occurredAt: "2026-11-14T09:11:00",
          title: "아몬드",
          subtitle: "[p.102] 인물이 아주 무심하게 성장해 간다.",
          previewText: "[p.102] 인물이 아주 무심하게 성장해 간다.",
          targetId: 8016,
        },
      ],
    },
    {
      year: 2026,
      showYear: false,
      monthDay: "10.31",
      items: [
        {
          timelineId: 2017,
          type: "REGISTER",
          occurredAt: "2026-10-31T11:20:00",
          title: "불편한 편의점",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8017,
        },
        {
          timelineId: 2018,
          type: "STATUS",
          occurredAt: "2026-10-31T14:35:00",
          title: "독서 상태 변경",
          subtitle: "읽는 중으로 바뀌었어요.",
          previewText: "읽는 중으로 바뀌었어요.",
          targetId: 8018,
        },
        {
          timelineId: 2019,
          type: "FOCUS",
          occurredAt: "2026-10-31T23:02:00",
          title: "2시간 4분의 포커스",
          subtitle: "20:58 - 23:02",
          previewText: "2시간 4분의 포커스",
          targetId: 8019,
        },
        {
          timelineId: 2020,
          type: "RECORD",
          occurredAt: "2026-10-31T23:10:00",
          title: "불편한 편의점",
          subtitle: "[p.174] 익숙한 공간이 다른 의미로 보이기 시작했다.",
          previewText: "[p.174] 익숙한 공간이 다른 의미로 보이기 시작했다.",
          targetId: 8020,
        },
      ],
    },
    {
      year: 2026,
      showYear: false,
      monthDay: "09.18",
      items: [
        {
          timelineId: 2021,
          type: "FOCUS",
          occurredAt: "2026-09-18T07:55:00",
          title: "31분의 포커스",
          subtitle: "07:24 - 07:55",
          previewText: "31분의 포커스",
          targetId: 8021,
        },
        {
          timelineId: 2022,
          type: "STATUS",
          occurredAt: "2026-09-18T08:00:00",
          title: "독서 상태 변경",
          subtitle: "읽고 싶어요로 바뀌었어요.",
          previewText: "읽고 싶어요로 바뀌었어요.",
          targetId: 8022,
        },
        {
          timelineId: 2023,
          type: "REGISTER",
          occurredAt: "2026-09-18T12:40:00",
          title: "채식주의자",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8023,
        },
      ],
    },
    {
      year: 2026,
      showYear: false,
      monthDay: "08.03",
      items: [
        {
          timelineId: 2024,
          type: "RECORD",
          occurredAt: "2026-08-03T21:44:00",
          title: "채식주의자",
          subtitle: "[p.39] 낯선 선택이 주는 긴장이 선명했다.",
          previewText: "[p.39] 낯선 선택이 주는 긴장이 선명했다.",
          targetId: 8024,
        },
        {
          timelineId: 2025,
          type: "FOCUS",
          occurredAt: "2026-08-03T22:30:00",
          title: "47분의 포커스",
          subtitle: "21:43 - 22:30",
          previewText: "47분의 포커스",
          targetId: 8025,
        },
        {
          timelineId: 2026,
          type: "STATUS",
          occurredAt: "2026-08-03T22:31:00",
          title: "독서 상태 변경",
          subtitle: "읽는 중으로 바뀌었어요.",
          previewText: "읽는 중으로 바뀌었어요.",
          targetId: 8026,
        },
      ],
    },
    {
      year: 2026,
      showYear: false,
      monthDay: "07.11",
      items: [
        {
          timelineId: 2027,
          type: "REGISTER",
          occurredAt: "2026-07-11T09:30:00",
          title: "파친코 1",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8027,
        },
        {
          timelineId: 2028,
          type: "RECORD",
          occurredAt: "2026-07-11T23:12:00",
          title: "파친코 1",
          subtitle: "[p.94] 가족 이야기의 밀도가 생각보다 깊다.",
          previewText: "[p.94] 가족 이야기의 밀도가 생각보다 깊다.",
          targetId: 8028,
        },
        {
          timelineId: 2029,
          type: "FOCUS",
          occurredAt: "2026-07-11T23:10:00",
          title: "1시간 19분의 포커스",
          subtitle: "21:51 - 23:10",
          previewText: "1시간 19분의 포커스",
          targetId: 8029,
        },
      ],
    },
    {
      year: 2026,
      showYear: false,
      monthDay: "06.22",
      items: [
        {
          timelineId: 2030,
          type: "STATUS",
          occurredAt: "2026-06-22T08:13:00",
          title: "독서 상태 변경",
          subtitle: "완독으로 바뀌었어요.",
          previewText: "완독으로 바뀌었어요.",
          targetId: 8030,
        },
        {
          timelineId: 2031,
          type: "RECORD",
          occurredAt: "2026-06-22T20:44:00",
          title: "파친코 1",
          subtitle: "[p.321] 긴 시간의 이동이 인물의 표정처럼 느껴졌다.",
          previewText: "[p.321] 긴 시간의 이동이 인물의 표정처럼 느껴졌다.",
          targetId: 8031,
        },
        {
          timelineId: 2032,
          type: "FOCUS",
          occurredAt: "2026-06-22T22:01:00",
          title: "1시간 8분의 포커스",
          subtitle: "20:53 - 22:01",
          previewText: "1시간 8분의 포커스",
          targetId: 8032,
        },
        {
          timelineId: 2033,
          type: "REGISTER",
          occurredAt: "2026-06-22T22:10:00",
          title: "파친코 2",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8033,
        },
      ],
    },
    {
      year: 2025,
      showYear: true,
      monthDay: "12.18",
      items: [
        {
          timelineId: 2034,
          type: "REGISTER",
          occurredAt: "2025-12-18T18:30:00",
          title: "이처럼 사소한 것들",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8034,
        },
        {
          timelineId: 2035,
          type: "STATUS",
          occurredAt: "2025-12-18T18:31:00",
          title: "독서 상태 변경",
          subtitle: "읽는 중으로 바뀌었어요.",
          previewText: "읽는 중으로 바뀌었어요.",
          targetId: 8035,
        },
        {
          timelineId: 2036,
          type: "FOCUS",
          occurredAt: "2025-12-18T21:07:00",
          title: "39분의 포커스",
          subtitle: "20:28 - 21:07",
          previewText: "39분의 포커스",
          targetId: 8036,
        },
      ],
    },
    {
      year: 2025,
      showYear: false,
      monthDay: "11.30",
      items: [
        {
          timelineId: 2037,
          type: "REGISTER",
          occurredAt: "2025-11-30T09:00:00",
          title: "첫사랑의 침공",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8037,
        },
        {
          timelineId: 2038,
          type: "RECORD",
          occurredAt: "2025-11-30T22:30:00",
          title: "첫사랑의 침공",
          subtitle: "[p.17] 가볍게 읽히는데 묘하게 계속 남는다.",
          previewText: "[p.17] 가볍게 읽히는데 묘하게 계속 남는다.",
          targetId: 8038,
        },
      ],
    },
    {
      year: 2025,
      showYear: false,
      monthDay: "10.12",
      items: [
        {
          timelineId: 2039,
          type: "FOCUS",
          occurredAt: "2025-10-12T06:58:00",
          title: "24분의 포커스",
          subtitle: "06:34 - 06:58",
          previewText: "24분의 포커스",
          targetId: 8039,
        },
        {
          timelineId: 2040,
          type: "STATUS",
          occurredAt: "2025-10-12T07:00:00",
          title: "독서 상태 변경",
          subtitle: "잠시 멈춤으로 바뀌었어요.",
          previewText: "잠시 멈춤으로 바뀌었어요.",
          targetId: 8040,
        },
        {
          timelineId: 2041,
          type: "REGISTER",
          occurredAt: "2025-10-12T20:22:00",
          title: "모순",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8041,
        },
      ],
    },
    {
      year: 2025,
      showYear: false,
      monthDay: "09.01",
      items: [
        {
          timelineId: 2042,
          type: "RECORD",
          occurredAt: "2025-09-01T21:01:00",
          title: "모순",
          subtitle: "[p.70] 평범한 장면이 오히려 더 아프게 남는다.",
          previewText: "[p.70] 평범한 장면이 오히려 더 아프게 남는다.",
          targetId: 8042,
        },
        {
          timelineId: 2043,
          type: "FOCUS",
          occurredAt: "2025-09-01T22:18:00",
          title: "1시간 2분의 포커스",
          subtitle: "21:16 - 22:18",
          previewText: "1시간 2분의 포커스",
          targetId: 8043,
        },
        {
          timelineId: 2044,
          type: "STATUS",
          occurredAt: "2025-09-01T22:19:00",
          title: "독서 상태 변경",
          subtitle: "읽는 중으로 바뀌었어요.",
          previewText: "읽는 중으로 바뀌었어요.",
          targetId: 8044,
        },
        {
          timelineId: 2045,
          type: "RECORD",
          occurredAt: "2025-09-01T22:25:00",
          title: "모순",
          subtitle: "[p.148] 인물의 말보다 침묵이 더 크게 느껴졌다.",
          previewText: "[p.148] 인물의 말보다 침묵이 더 크게 느껴졌다.",
          targetId: 8045,
        },
      ],
    },
    {
      year: 2025,
      showYear: false,
      monthDay: "07.26",
      items: [
        {
          timelineId: 2046,
          type: "REGISTER",
          occurredAt: "2025-07-26T11:11:00",
          title: "데미안",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8046,
        },
        {
          timelineId: 2047,
          type: "FOCUS",
          occurredAt: "2025-07-26T23:00:00",
          title: "1시간 34분의 포커스",
          subtitle: "21:26 - 23:00",
          previewText: "1시간 34분의 포커스",
          targetId: 8047,
        },
        {
          timelineId: 2048,
          type: "RECORD",
          occurredAt: "2025-07-26T23:05:00",
          title: "데미안",
          subtitle: "[p.55] 문장이 단단해서 천천히 읽게 된다.",
          previewText: "[p.55] 문장이 단단해서 천천히 읽게 된다.",
          targetId: 8048,
        },
      ],
    },
    {
      year: 2025,
      showYear: false,
      monthDay: "05.03",
      items: [
        {
          timelineId: 2049,
          type: "STATUS",
          occurredAt: "2025-05-03T10:00:00",
          title: "독서 상태 변경",
          subtitle: "완독으로 바뀌었어요.",
          previewText: "완독으로 바뀌었어요.",
          targetId: 8049,
        },
        {
          timelineId: 2050,
          type: "REGISTER",
          occurredAt: "2025-05-03T10:05:00",
          title: "위저드 베이커리",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8050,
        },
        {
          timelineId: 2051,
          type: "FOCUS",
          occurredAt: "2025-05-03T22:49:00",
          title: "52분의 포커스",
          subtitle: "21:57 - 22:49",
          previewText: "52분의 포커스",
          targetId: 8051,
        },
      ],
    },
    {
      year: 2024,
      showYear: true,
      monthDay: "12.24",
      items: [
        {
          timelineId: 2052,
          type: "REGISTER",
          occurredAt: "2024-12-24T14:12:00",
          title: "여름은 오래 그곳에 남아",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8052,
        },
        {
          timelineId: 2053,
          type: "STATUS",
          occurredAt: "2024-12-24T14:13:00",
          title: "독서 상태 변경",
          subtitle: "읽고 싶어요로 바뀌었어요.",
          previewText: "읽고 싶어요로 바뀌었어요.",
          targetId: 8053,
        },
        {
          timelineId: 2054,
          type: "RECORD",
          occurredAt: "2024-12-24T21:49:00",
          title: "여름은 오래 그곳에 남아",
          subtitle: "[p.28] 계절의 공기가 유난히 세밀하게 느껴졌다.",
          previewText: "[p.28] 계절의 공기가 유난히 세밀하게 느껴졌다.",
          targetId: 8054,
        },
      ],
    },
    {
      year: 2024,
      showYear: false,
      monthDay: "10.10",
      items: [
        {
          timelineId: 2055,
          type: "FOCUS",
          occurredAt: "2024-10-10T07:20:00",
          title: "18분의 포커스",
          subtitle: "07:02 - 07:20",
          previewText: "18분의 포커스",
          targetId: 8055,
        },
        {
          timelineId: 2056,
          type: "REGISTER",
          occurredAt: "2024-10-10T19:10:00",
          title: "희랍어 시간",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8056,
        },
        {
          timelineId: 2057,
          type: "RECORD",
          occurredAt: "2024-10-10T23:01:00",
          title: "희랍어 시간",
          subtitle: "[p.63] 말보다 침묵이 더 많은 장면이었다.",
          previewText: "[p.63] 말보다 침묵이 더 많은 장면이었다.",
          targetId: 8057,
        },
        {
          timelineId: 2058,
          type: "STATUS",
          occurredAt: "2024-10-10T23:02:00",
          title: "독서 상태 변경",
          subtitle: "읽는 중으로 바뀌었어요.",
          previewText: "읽는 중으로 바뀌었어요.",
          targetId: 8058,
        },
      ],
    },
    {
      year: 2024,
      showYear: false,
      monthDay: "08.15",
      items: [
        {
          timelineId: 2059,
          type: "FOCUS",
          occurredAt: "2024-08-15T22:42:00",
          title: "1시간 11분의 포커스",
          subtitle: "21:31 - 22:42",
          previewText: "1시간 11분의 포커스",
          targetId: 8059,
        },
        {
          timelineId: 2060,
          type: "RECORD",
          occurredAt: "2024-08-15T22:43:00",
          title: "희랍어 시간",
          subtitle: "[p.144] 조용한데도 아주 강한 장면이었다.",
          previewText: "[p.144] 조용한데도 아주 강한 장면이었다.",
          targetId: 8060,
        },
        {
          timelineId: 2061,
          type: "STATUS",
          occurredAt: "2024-08-15T22:45:00",
          title: "독서 상태 변경",
          subtitle: "완독으로 바뀌었어요.",
          previewText: "완독으로 바뀌었어요.",
          targetId: 8061,
        },
      ],
    },
    {
      year: 2024,
      showYear: false,
      monthDay: "06.02",
      items: [
        {
          timelineId: 2062,
          type: "REGISTER",
          occurredAt: "2024-06-02T12:01:00",
          title: "82년생 김지영",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8062,
        },
        {
          timelineId: 2063,
          type: "FOCUS",
          occurredAt: "2024-06-02T15:25:00",
          title: "37분의 포커스",
          subtitle: "14:48 - 15:25",
          previewText: "37분의 포커스",
          targetId: 8063,
        },
        {
          timelineId: 2064,
          type: "RECORD",
          occurredAt: "2024-06-02T21:11:00",
          title: "82년생 김지영",
          subtitle: "[p.91] 익숙해서 더 쉽게 지나칠 수 없는 이야기였다.",
          previewText: "[p.91] 익숙해서 더 쉽게 지나칠 수 없는 이야기였다.",
          targetId: 8064,
        },
      ],
    },
    {
      year: 2024,
      showYear: false,
      monthDay: "03.17",
      items: [
        {
          timelineId: 2065,
          type: "STATUS",
          occurredAt: "2024-03-17T08:00:00",
          title: "독서 상태 변경",
          subtitle: "읽고 싶어요로 바뀌었어요.",
          previewText: "읽고 싶어요로 바뀌었어요.",
          targetId: 8065,
        },
        {
          timelineId: 2066,
          type: "REGISTER",
          occurredAt: "2024-03-17T08:05:00",
          title: "아주 희미한 빛으로도",
          subtitle: "서재에 등록했어요.",
          previewText: "서재에 등록했어요.",
          targetId: 8066,
        },
        {
          timelineId: 2067,
          type: "FOCUS",
          occurredAt: "2024-03-17T23:30:00",
          title: "2시간 1분의 포커스",
          subtitle: "21:29 - 23:30",
          previewText: "2시간 1분의 포커스",
          targetId: 8067,
        },
        {
          timelineId: 2068,
          type: "RECORD",
          occurredAt: "2024-03-17T23:35:00",
          title: "아주 희미한 빛으로도",
          subtitle: "[p.203] 사소한 장면이 오래 남아 자꾸 되돌아보게 된다.",
          previewText: "[p.203] 사소한 장면이 오래 남아 자꾸 되돌아보게 된다.",
          targetId: 8068,
        },
      ],
    },
  ];

  return (
    <div className="flex flex-col h-full w-full items-center justify-center pb-10">
      <TopNavigation
        left={<img src={chevron_left} alt="back" />}
        onClickLeft={() => window.history.back()}
        center="독서 히스토리"
        className="mb-10"
      />
      <div className="flex flex-col gap-4 w-full">
        {historyData.map((yearGroup) => (
          <div key={yearGroup.year} className="flex gap-2 items-start">
            <ResourceDate
              topText={yearGroup.monthDay}
              bottomText={yearGroup.showYear ? String(yearGroup.year) : ""}
            />{" "}
            <div className="min-w-0 flex flex-1 flex-col gap-1">
              {yearGroup.items.map((item) => (
                <HistoryInfoCard
                  key={item.timelineId}
                  variant={item.type === "RECORD" ? "history" : "time"}
                  title={item.title}
                  time={item.subtitle}
                  hasIcon={item.type !== "REGISTER" && item.type !== "STATUS"}
                />
              ))}{" "}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
